version: "3"

services:
  server:
    build: ./eshop-api
    container_name: server
    environment:
      - MONGO_URI=mongodb://localhost:27017/nest
      - MONGO_URI_TEST=mongodb://localhost:27017/test
    command: npm start
    restart: unless-stopped
    ports:
      - '5000:5000'
    depends_on: 
      - mongo

  client:
    build: ./eshop
    container_name: client
    restart: unless-stopped
    command: serve -s build -l 3000
    ports:
      - '3000:3000'

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    
  # nginx:
  #   image: nginx:stable-alpine
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
  #     - /etc/letsencrypt/archive/mymanager.com/fullchain7.pem:/etc/letsencrypt/live/mymanager.com/fullchain.pem
  #     - /etc/letsencrypt/archive/mymanager.com/privkey7.pem:/etc/letsencrypt/live/mymanager.com/privkey.pem
  #     - ./ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem
  #   restart: unless-stopped
  #   depends_on:
  #     - client
  #     - admin
  #     - server
