version: "3"

services:
  server:
    build: ./eshop-api
    container_name: server
    environment:
      - MONGO_URI=mongodb://mongo:27017/nest
      - MONGO_URI_TEST=mongodb://mongo:27017/test
    command: npm start
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  client:
    build: ./eshop
    container_name: client
    restart: unless-stopped
    command: serve -s build -l 3000
    ports:
      - "3000:3000"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
